// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnJpewTrdH9B4arZ9Q_hZhWElH5vUVmXc',
    appId: '1:1025732640895:web:542e1aa01c441929343f4a',
    messagingSenderId: '1025732640895',
    projectId: 'giveit-takeit',
    authDomain: 'giveit-takeit.firebaseapp.com',
    storageBucket: 'giveit-takeit.appspot.com',
    measurementId: 'G-KPZNHSC527',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq1aoTH_yEduSHH_7g9xgFAiYQP_jk3Tk',
    appId: '1:1025732640895:android:993ed9dae212e555343f4a',
    messagingSenderId: '1025732640895',
    projectId: 'giveit-takeit',
    storageBucket: 'giveit-takeit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoyFgOBxjsfsQBvuNXJ3SepQbkhLdTDOI',
    appId: '1:1025732640895:ios:f13f7102dde7f8a7343f4a',
    messagingSenderId: '1025732640895',
    projectId: 'giveit-takeit',
    storageBucket: 'giveit-takeit.appspot.com',
    androidClientId: '1025732640895-rrifuv58qsahmjen7bhd5cktg92foo1g.apps.googleusercontent.com',
    iosClientId: '1025732640895-snrmvijk42p4g6hlgni0ns99ir8sdmns.apps.googleusercontent.com',
    iosBundleId: 'com.example.giveitTakeit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoyFgOBxjsfsQBvuNXJ3SepQbkhLdTDOI',
    appId: '1:1025732640895:ios:7e4ee8fa1b4ab580343f4a',
    messagingSenderId: '1025732640895',
    projectId: 'giveit-takeit',
    storageBucket: 'giveit-takeit.appspot.com',
    androidClientId: '1025732640895-rrifuv58qsahmjen7bhd5cktg92foo1g.apps.googleusercontent.com',
    iosClientId: '1025732640895-qq5b7rdghcjqpm3ng6d8mg54bnnqg58n.apps.googleusercontent.com',
    iosBundleId: 'com.example.giveitTakeit.RunnerTests',
  );
}


